#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_auth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

#config/routes.yaml
api_auth_login:
  path: /api/auth/login
  methods:  [POST]

api:
  prefix: /api
  resource: '../src/Controller/Api'